### ISSUE TITLE
Question: ordersModel and userSchema

### ISSUE THREAD

**Issue by ioanniswd** [Cyb3rN4u7/AWS-Orders#1]
Are those files used with API body mapping?

**Comment by achimoraites** [comment]
Yes they are used to validate the request format before calling the lambda

![orders-model-img](https://user-images.githubusercontent.com/4193340/49532538-64e86e00-f8c5-11e8-9125-c665a48e84ae.png)

![requestvalidator](https://user-images.githubusercontent.com/4193340/49532469-3cf90a80-f8c5-11e8-8974-5a925b2f42ca.png)
