### ISSUE TITLE
Cost reduction

### ISSUE THREAD

**Issue by ioanniswd** [Cyb3rN4u7/AWS-Orders#2]
Query for users last order can be performed with a composite sort key in a Local Secondary Index, a GSI is not required.

**Comment by Cyb3rN4u7** [comment]
Should i assume we have one store and only one user?

**Comment by achimoraites** [comment]
Should i assume we perform query for a requested store and user ?
I have changed the implementation to reflect that

**Comment by ioanniswd** [comment]
The query performed now will return the last 5 orders of ALL users in that store, and filter them by the user id. 

1. Filtering can occur in query with a FilterExpression. Note that this does not change the capacity used to query the table.
 
2. A different sort key is required to query the last orders of a specific user. Check composite keys and best practices: https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/bp-sort-keys.html

```
    const params=  {
      TableName:'StoreOrders',
      IndexName: 'store_id-timestamp-index', 
      ScanIndexForward: false,           
      Limit: 5,
      KeyConditionExpression: "store_id = :sid and #time < :t",
      ExpressionAttributeNames:{
        "#time": "timestamp"
      },
      ExpressionAttributeValues: {
        ":sid" : store_id,
        ":t": Date.now()
      }
    };
   
    console.log(user_id);
    // this solution is more elegant!
    const orders = await dynamoDC.query(params).promise();
   
    const userOrders = orders.Items.filter(order =>{
      return order.user_id === user_id;
    });
```

**Comment by achimoraites** [comment]
Thank you for your feedback!

**Comment by Cyb3rN4u7** [comment]
should i change the timestamp to timestamp#user_id ?

**Comment by achimoraites** [comment]
Should i store the user_id in the timestamp ?
 user_id#timestamp 
user1#1544089705922
OR
timestamp#user_id
1544089705922#user1

**Comment by achimoraites** [comment]
Feature has been implemented
